export const ApodActionTypes = {
    FETCH_IMAGE_BEGIN: "FETCH_IMAGE_BEGIN",
    FETCH_IMAGE_SUCCESS: "FETCH_IMAGE_SUCCESS",
    FETCH_IMAGE_FAILURE: "FETCH_IMAGE_FAILURE",
    SET_CURRENT_DATE: "SET_CURRENT_DATE",
    NEXT_DATE_DAY: "NEXT_DATE_DAY",
    PREV_DATE_DAY: "PREV_DATE_DAY"

}
